sudo: false
language: scala
scala:
  - 2.12.7
  - 2.11.12
jdk:
  - oraclejdk8

before_cache:
  - find $HOME/.sbt -name "*.lock" | xargs rm
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm

stages:
  - name: compile
  - name: test

jobs:
  include:
    - stage: compile
      script: sbt clean compile
    - stage: test
      script: sbt ++$TRAVIS_SCALA_VERSION test
      