sudo: false
language: scala
scala:
  - 2.11.12
jdk:
  - oraclejdk8

env:
  - JOB=Test

script:
  - sbt clean compile test

stages:
  - name: compile
  - name: test

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt

before_cache:
  - rm -fv $HOME/.ivy2/.sbt.ivy.lock
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt        -name "*.lock"               -print -delete
